
package edu.kit.aifb.eorg.datacollector.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DataCollectorService", targetNamespace = "http://datacollector.eorg.aifb.kit.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataCollectorService {


    /**
     * 
     * @param senderIdentifier
     * @param durationInMillis
     * @param testrunID
     */
    @WebMethod
    @RequestWrapper(localName = "publishData", targetNamespace = "http://datacollector.eorg.aifb.kit.edu/", className = "edu.kit.aifb.eorg.datacollector.client.PublishData")
    @ResponseWrapper(localName = "publishDataResponse", targetNamespace = "http://datacollector.eorg.aifb.kit.edu/", className = "edu.kit.aifb.eorg.datacollector.client.PublishDataResponse")
    public void publishData(
        @WebParam(name = "senderIdentifier", targetNamespace = "")
        String senderIdentifier,
        @WebParam(name = "durationInMillis", targetNamespace = "")
        long durationInMillis,
        @WebParam(name = "testrunID", targetNamespace = "")
        String testrunID);

}
